version: '2'
services:
  app:
    build: ./app
    ports:
      - '80:80'
    depends_on:
      - api
  api:
    build: ./api
    ports:
      - '8080:8080'
    depends_on:
      - mongo
    environment:
      - MONGODB_URL=mongodb://mongo:27017/survey-testing
  mongo:
    image: mongo
    ports:
      - '27017:27017'