version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - 443:443
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
  app:
    build: ./app
    ports:
      - 3000:80
    depends_on:
      - api
    environment:
      - VIRTUAL_HOST=app.screver.kenstack.io
  api:
    build: ./api
    ports:
      - 8080:8080
    depends_on:
      - mongo
    environment:
      - MONGODB_URL=mongodb://mongo:27017/survey-testing
      - VIRTUAL_HOST=api.screver.kenstack.io
  mongo:
    image: mongo
    ports:
      - '27017:27017'
